[project]
name = "nlp-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.59.3",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "selectolax>=0.3.27",
]
